query GetEventById($getEventByIdId: String!) {
  getEventById(id: $getEventByIdId) {
    createdAt
    description
    detail
    eventFormat
    eventType {
      id
      name
    }
    id
    img
    isTemplate
    name
    rental {
      customLocation
      devices {
        availableQuantity
        createdAt
        description
        hourlyRentalFee
        id
        img
        name
        quantity
      }
      event {
        createdAt
        description
        detail
        eventFormat
        id
        img
        isTemplate
        name
      }
      humanResources {
        availableQuantity
        createdAt
        description
        hourlySalary
        id
        img
        name
        quantity
      }
      id
      locations {
        address
        createdAt
        description
        hourlyRentalFee
        id
        img
        name
      }
      rentalEndTime
      rentalStartTime
      timelines {
        description
        id
        startTime
      }
      totalPrice
      user {
        avatar
        createdAt
        dob
        email
        firstName
        gender
        id
        lastName
        phoneNumber
        role {
          id
          name
        }
        roleId
        status
        updatedAt
      }
    }
  }
}
