query GetMyContracts($queryParams: GetContractsRequest!) {
  getMyContracts(queryParams: $queryParams) {
    items {
      createdAt
      customer {
        address
        id
        name
        phoneNumber
      }
      id
      name
      rental {
        devices {
          availableQuantity
          description
          hourlyRentalFee
          id
          img
          name
          quantity
        }
        humanResources {
          availableQuantity
          description
          hourlySalary
          id
          img
          name
          quantity
        }
        id
        locations {
          address
          description
          hourlyRentalFee
          id
          img
          name
        }
        rentalEndTime
        rentalStartTime
        totalPrice
        user {
          avatar
          createdAt
          dob
          email
          firstName
          gender
          id
          lastName
          phoneNumber
          role {
            id
            name
          }
          roleId
          updatedAt
        }
      }
      singingDate
      status
    }
    meta {
      currentPage
      itemCount
      itemsPerPage
      totalItems
      totalPages
    }
  }
}